{
  "openapi": "3.0.0",
  "info": {
    "title": "NGSI/DWD-middleware UAT",
    "version": "1.0.0",
    "description": ""
  },
  "servers": [
    {
      "url": "https://api.dwd-uat.netglobalsolutions.net"
    }
  ],
  "paths": {
    "/generate-token": {
      "get": {
        "summary": "generate-token",
         "description": "This view is for **Merchants**.\n\nIt uses **JWT** as the default authentication scheme.\n\nReturns a `token` if the user is authenticated.\n\nThe following headers are required:\n- `X-API-KEY`\n- `X-API-USERNAME`\n- `X-API-PASSWORD`\n\nTo access protected resources, set:\n\nHTTP_AUTHORIZATION: Bearer {{token}}",
        "parameters": [
          {
            "name": "X-API-KEY",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "{{X-API-KEY}}"
          },
          {
            "name": "X-API-USERNAME",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "{{X-API-USERNAME}}"
          },
          {
            "name": "X-API-PASSWORD",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "{{X-API-PASSWORD}}"
          }
        ],
        "responses": {
          "201": {
            "description": "generate-token",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "boolean"
                    },
                    "status_code": {
                      "type": "integer"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "token": {
                          "type": "string"
                        },
                        "exp": {
                          "type": "string",
                          "format": "style"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "status": true,
                  "status_code": 201,
                  "message": "create",
                  "data": {
                    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJBY2Nlc3MiOiJ0cnVlIiwiYWNjb3VudF9pZCI6IjEiLCJpYXQiOjE3NzQ4NjEzMDgsIm5iZiI6MTc3NDg2MTMwOCwiZXhwIjoxNzc0ODY0OTA4fQ.WJW5JBM_UbLfVxqUIN18wgrRhTV_sMYu5PXO33CvPZA",
                    "exp": "2026-03-30 18:01:48"
                  }
                }
              }
            }
          },
          "403": {
            "description": "generate-token-failed",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "boolean"
                    },
                    "status_code": {
                      "type": "integer"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "status": false,
                  "status_code": 403,
                  "message": "This API access is invalid"
                }
              }
            }
          }
        }
      }
    },
    "/v1/payment": {
      "post": {
        "summary": "/v1/payment",
        "parameters": [
          {
            "name": "X-API-KEY",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "{{X-API-KEY}}"
          },
          {
            "name": "X-API-USERNAME",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "{{X-API-USERNAME}}"
          },
          {
            "name": "X-API-PASSWORD",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "{{X-API-PASSWORD}}"
          }
        ],
        "responses": {
          "201": {
            "description": "/v1/payment",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    },
                    "amount": {
                      "type": "string"
                    },
                    "fee": {
                      "type": "string",
                      "format": "utc-millisec"
                    },
                    "total_txn_amount": {
                      "type": "number"
                    },
                    "reference_number": {
                      "type": "string"
                    },
                    "txn_reference": {
                      "type": "string"
                    },
                    "create_at": {
                      "type": "string",
                      "format": "date-time"
                    },
                    "raw_string": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "status": true,
                  "status_code": 201,
                  "message": "Created Successfully!",
                  "amount": "775.04",
                  "fee": "20",
                  "total_txn_amount": 795.04,
                  "reference_number": "11Wsds4w223",
                  "txn_reference": "202611Wsds4w223",
                  "create_at": "2026-03-30T17:52:56.000+08:00",
                  "raw_string": "00020101021228760011ph.ppmi.p2m0111OPDVPHM1XXX03157771480000000840416529481372571650105030015204601653036085406795.045802PH5909Netglobal6015City Of Mandalu62390010ph.allbank0521442026202611Wsds4w22388310012ph.ppmi.qrph0111OPDVPHM1XXX63046768"
                }
              }
            }
          },
          "401": {
            "description": "/v1/payment already exist",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "boolean"
                    },
                    "status_code": {
                      "type": "integer"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "status": false,
                  "status_code": 401,
                  "message": "reference_number already exist"
                }
              }
            }
          },
          "403": {
            "description": "/v1/payment invalid api access",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "boolean"
                    },
                    "status_code": {
                      "type": "integer"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "status": false,
                  "status_code": 403,
                  "message": "This API access is invalid"
                }
              }
            }
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "amount": {
                    "type": "string"
                  },
                  "reference_number": {
                    "type": "string"
                  },
                  "acount_no": {
                    "type": "string",
                    "format": "utc-millisec"
                  },
                  "phone_number": {
                    "type": "string",
                    "format": "utc-millisec"
                  },
                  "email": {
                    "type": "string",
                    "format": "email"
                  }
                }
              },
              "example": {
                "amount": "775.04",
                "reference_number": "11Wsds4w223",
                "acount_no": "103501992811",
                "phone_number": "09123456789",
                "email": "test@gmail.com"
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  }
}