{
  "openapi": "3.0.0",
  "info": {
    "title": "NGSI Cashout Direct",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://api.ngsi-pgw-uat.netglobalsolutions.net"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "tags": [
    {
      "name": "Generate Token"
    },
    {
      "name": "Payment Channel"
    },
    {
      "name": "Cashout Transaction Status"
    },
    {
      "name": "Cashout"
    }
  ],
  "paths": {
    "/v1/cashout": {
      "post": {
        "tags": [
          "Cashout"
        ],
        "summary": "Cashout Disbusment",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "reference_number": "1WY32456781581",
                  "callback_url": "https://api.ngsi-pgw-uat.netglobalsolutions.net/motify/service_requests",
                  "merchant_details": {
                    "txn_amount": 100,
                    "name": "johndoe",
                    "bank_code": "G-1001",
                    "account_number": "09213456789",
                    "txn_type": "2"
                  },
                  "email_confirmation": {
                    "email": "rhonbhorj@gmail.com",
                    "auto": "off"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "X-API-KEY",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "{{X-API-KEY}}"
          },
          {
            "name": "X-API-USERNAME",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "{{X-API-USERNAME}}"
          },
          {
            "name": "X-API-PASSWORD",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "{{X-API-PASSWORD}}"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": true,
                  "message": "Transaction is on process.",
                  "data": {
                    "reference_number": "1WY32456781581",
                    "create_at": "2025-11-08T18:28:36.000+08:00",
                    "txn_ref": "3020251WY32456781581",
                    "txn_amount": "100"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": false,
                  "message": "Transaction with this client ref (1WY32456781581) already exists."
                }
              }
            }
          }
        }
      }
    },
    "/payment-channel": {
      "get": {
        "tags": [
          "Payment Channel"
        ],
        "summary": "bank list",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "X-API-KEY",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "{{X-API-KEY}}"
          },
          {
            "name": "X-API-USERNAME",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "{{X-API-USERNAME}}"
          },
          {
            "name": "X-API-PASSWORD",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "{{X-API-PASSWORD}}"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": true,
                  "message": "success",
                  "data": [
                    {
                      "gateway": "instapay",
                      "channel_code": "1102",
                      "name": "Asia United Bank Corporation"
                    },
                    {
                      "gateway": "pesonet",
                      "channel_code": "1322",
                      "name": "UNO BANK"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/cashout-transaction-status": {
      "post": {
        "tags": [
          "Cashout Transaction Status"
        ],
        "summary": "cashout transaction status",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "reference_number": "dz110UAT1198-1q"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "X-API-KEY",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "{{X-API-KEY}}"
          },
          {
            "name": "X-API-USERNAME",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "{{X-API-USERNAME}}"
          },
          {
            "name": "X-API-PASSWORD",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "{{X-API-PASSWORD}}"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": true,
                  "data": {
                    "transaction_status": "PENDING",
                    "transaction_type": "cashout",
                    "amount": "201",
                    "reference_number": "dz110UAT1198-1",
                    "transaction_Reference": "302025dz110UAT1198-1",
                    "date_quested": "2025-11-07 15:14:21",
                    "date_modified": ""
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": false,
                  "message": "No data found"
                }
              }
            }
          }
        }
      }
    },
    "/generate-token": {
      "get": {
        "tags": [
          "Generate Token"
        ],
        "summary": "Generate Token",
        "description": "This view is for **Merchants**.\n\nIt uses **JWT** as the default authentication scheme.\n\nReturns a `token` if the user is authenticated.\n\nThe following headers are required:\n- `X-API-KEY`\n- `X-API-USERNAME`\n- `X-API-PASSWORD`\n\nTo access protected resources, set:\n\nHTTP_AUTHORIZATION: Bearer {{token}}",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "X-API-KEY",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "{{X-API-KEY}}"
          },
          {
            "name": "X-API-USERNAME",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "{{X-API-USERNAME}}"
          },
          {
            "name": "X-API-PASSWORD",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "{{X-API-PASSWORD}}"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": true,
                  "message": "create",
                  "data": {
                    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJBY2Nlc3MiOiJ0cnVlIiwiYWFjY291bnRfaWQiOiIzMSIsImlhdCI6MTc2MTI4NjA1MSwibmJmIjoxNzYxMjg2MDUxLCJleHAiOjE3NjEyODk2NTF9.gzCvQblNA3_gAje7oMbkA0YOHv3sEP9IHQZddlYgJdc"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": false,
                  "message": "Api key is invalid"
                }
              }
            }
          }
        }
      }
    }
  }
}