openapi: 3.0.0
info:
  title: 'NGSI PAYGATE API Documentation '
  description: This contains API Documentation for Transaction Service
  version: 1.0.0
servers:
  - url: https://api.dev.ngsiwallet.net
  - url: http://{{baseurl}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: pgw
  - name: pgw > api
  - name: pgw > api > v1
  - name: pgw > api > v1 > auth
  - name: pgw > api > v1 > auth > obtain-token
  - name: pgw > api > v1 > transactions
  - name: pgw > api > v1 > transactions > new
  - name: pgw > api > v1 > transactions > qr-codes
  - name: pgw > api > v1 > transactions > qr-codes > details
  - name: pgw > api > v1 > transactions > qr-codes > generate
  - name: pgw > api > v1 > transactions > reference-number
  - name: pgw > api > v1 > transactions > statuses
  - name: pgw > api > v1 > transactions > types
paths:
  /pgw/api/v1/auth/obtain-token/:
    post:
      tags:
        - pgw > api > v1 > auth > obtain-token
      summary: Authenticate Merchant
      description: |-
        This view is for Merchants.

        It uses JWT as the default authencation scheme.

        Returns `token` if user is authenicated.



        A `username` and `secret` is required.

        Set `HTTP_AUTHORIZATION: Bearer {{token}}` to access resources.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: netglobalpay
                secret: wlq5fk#sv$3g75lejj4=&zyv8d&9b_x47!zq=ib35i&(elpqsb
                app_uuid: 0aa91257-2baa-437e-886c-d3cfce9552ce
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                data:
                  sit_13: {}
                message: <string>
        '400':
          description: Bad Request
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: <string>
        '401':
          description: Unauthorized
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: <string>
  /pgw/api/v1/transactions/new/:
    post:
      tags:
        - pgw > api > v1 > transactions > new
      summary: Create Transaction
      description: >-
        This method is used to create transaction.




        A `callback_uri` is required with format {hostname}/{endpoint}.


        The uri provied will be used by the Paygate to send update to the client
        regarding of the


        transaction status if response from the partners such as RBGI has been
        received.




        `reference_number`: must consist of <`mobile_number`> + <`epoch_time`>.




        Example:
        `https://api.dev.ngsiwallet.net/pgw/api/v1/transactions/postback`




        <pre>

        If success:


        {
            "message": "Success!",
        }


        Header status code must be set to 200.

        </pre>


        <pre>

        If failed:


        {
            "message": "Failed!",
            "errors: [ ... ]
        }


        Header status code must be set to 401.

        </pre>
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                app_uuid: 0aa91257-2baa-437e-886c-d3cfce9552ce
                paygate: 2
                txn_ref: '0017334354234244'
                endpoint: create-order
                particulars:
                  test: test
                callback_uri: ''
                merchant_details:
                  external_id: TEST-432224343
                  first_name: Test
                  last_name: Test
                  txn_amount: '1'
                  mobile_number: '1'
                  email_address: e@gmail.com
                  currency: PHP
                  locale: en
                  return_url: https://apipay-dendi.netglobalsolutions.cn/api/v3/success
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/x-www-form-urlencoded
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '201':
          description: Created
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                data:
                  sit_13: {}
                message: <string>
        '400':
          description: Bad Request
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: <string>
        '401':
          description: Unauthorized
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: <string>
        '403':
          description: Forbidden
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: <string>
        '409':
          description: Conflict
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: <string>
  /pgw/api/v1/transactions/qr-codes/details/:
    post:
      tags:
        - pgw > api > v1 > transactions > qr-codes > details
      summary: Check QR Code Details
      description: >-
        This endpoint determines if the QR Code String is valid. It also returns
        the data inside the QR code.
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                app_uuid:
                  type: string
                  description: '(Required) '
                  example: <string>
                raw_string:
                  type: string
                  description: '(Required) '
                  example: <string>
                reference_number:
                  type: string
                  description: '(Required) '
                  example: <string>
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/x-www-form-urlencoded
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                data:
                  sit_13: {}
                message: <string>
        '401':
          description: Unauthorized
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: <string>
  /pgw/api/v1/transactions/qr-codes/generate/:
    post:
      tags:
        - pgw > api > v1 > transactions > qr-codes > generate
      summary: Generate QR Code (P2P/P2M)
      description: >-
        A new QR code is generated if `reference_number` invalid, along,


        else it will retrieve and return back the exisitng one "Success!"
        message.




        A `callback_uri` must be is required with format {hostname}/{endpoint}.


        The uri provied will be used by the Paygate to send update to the client
        regarding of the


        transaction status if response from the partners such as RBGI has been
        received.



        `reference_number`: must consist of <`mobile_number`> + <`epoch_time`>.



        For static method, `txn_amount` can be set as 0 and `mobile_number` must
        be the name of the merchant.



        For `txn_type`, please refer to this endpoint:
        `/pgw/api/v1/transactions/types`



        Example:
        `https://api.dev.ngsiwallet.net/pgw/api/v1/transactions/postback`




        <pre>

        If success:


        {
            "message": "Success!",
        }


        Header status code must be set to 200.

        </pre>


        <pre>

        If failed:


        {
            "message": "Failed!",
            "errors: [ ... ]
        }


        Header status code must be set to 401.

        </pre>
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                app_uuid:
                  type: string
                  description: '(Required) '
                  example: 9bc89a03-9b35-4be0-b23e-c152bcacda29
                callback_uri:
                  type: string
                  description: '(Required) '
                  example: <string>
                eu0c:
                  type: string
                  description: '(Required) '
                  example: '[object Object]'
                payment_type:
                  type: string
                  description: '(Required) '
                  example: <string>
                reference_number:
                  type: string
                  description: '(Required) '
                  example: <string>
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/x-www-form-urlencoded
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                data:
                  sit_13: {}
                message: <string>
        '201':
          description: Created
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                data:
                  sit_13: {}
                message: <string>
        '400':
          description: Bad Request
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: <string>
        '401':
          description: Unauthorized
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: <string>
        '500':
          description: Internal Server Error
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: <string>
  /pgw/api/v1/transactions/reference-number/:
    post:
      tags:
        - pgw > api > v1 > transactions > reference-number
      summary: Retrieve Transaction by Reference Number
      description: Retrieve Transactions by reference number.
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                reference_number:
                  type: integer
                  description: '(Required) '
                  example: '1234567890'
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/x-www-form-urlencoded
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                data:
                  sit_13: {}
                message: <string>
        '400':
          description: Bad Request
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: <string>
        '401':
          description: Unauthorized
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: <string>
  /pgw/api/v1/transactions/statuses/:
    get:
      tags:
        - pgw > api > v1 > transactions > statuses
      summary: Get all Transaction Status
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                data:
                  sit_13: {}
                message: <string>
        '401':
          description: Unauthorized
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: <string>
        '403':
          description: Forbidden
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: <string>
  /pgw/api/v1/transactions/types/:
    get:
      tags:
        - pgw > api > v1 > transactions > types
      summary: Get all Transaction Types
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                data:
                  sit_13: {}
                message: <string>
        '401':
          description: Unauthorized
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: <string>
        '403':
          description: Forbidden
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: <string>